### ISSUE TITLE
Add new Language translation node

### ISSUE THREAD

**Issue by abalasu1** [node-red/node-red-bluemix-nodes#19]
machine translation service is deprecated and there is a new language translation service. Need node-red nodes for the language translation service.

**Comment by jthomas** [comment]
I'm going to start working on this shortly.

**Comment by abalasu1** [comment]
Hi James,

Is there a timeline for this? I have a SI partner who is using this in node-red and they are asking when this will be fixed.

Thanks,
Arun.

**Comment by jthomas** [comment]
I have the code changes done, I'm testing today and will hopefully push an update later on. It'll take a few days for the changes to be merged into the project and then pushed the Bluemix.
@knolleary

**Comment by knolleary** [comment]
I'm primed to get them published as soon as they are ready :+1:

**Comment by jthomas** [comment]
This has been resolved in the latest changes.
