### ISSUE TITLE
Remove Machine Translation and Language Identification

### ISSUE THREAD

**Issue by germanattanasio** [node-red/node-red-bluemix-nodes#22]
Please remove the IBM Watson Machine Translation and Language Identification nodes. 
This is related to #19 which is the service that replaces them.

**Comment by jthomas** [comment]
That ticket was actually resolved with 56007e60d3414da3eb5c1dac766b23bdd96dd149.
It's been left open accidentally, will sort that. 

Looking at https://github.com/node-red/node-red-bluemix-nodes/blob/master/watson/lid.js#L56-L71 and https://github.com/node-red/node-red-bluemix-nodes/blob/master/watson/smt.js#L83-L89 I believe we are now using the correct methods.

Can you confirm?

**Comment by germanattanasio** [comment]
@jthomas that looks **OK** :bowtie:
