### ISSUE TITLE
Relationship Extraction node - does it work ?

### ISSUE THREAD

**Issue by kwiatks** [node-red/node-red-bluemix-nodes#25]
Can't seem to get the Relationship Extraction node to work - can someone supply some simple test to confirm it is working ?

**Comment by jthomas** [comment]
I'll look into this for you.

**Comment by jthomas** [comment]
Okay, so the Relationship Extraction service used to return XML and now returns JSON by default. This has broken the node. It's a simple fix, so I'll push out a change shortly.

**Comment by dceejay** [comment]
Can it be told what to return ? So it can be fixed in case they change it again?
