### ISSUE TITLE
Change file type in Speech to Text node

### ISSUE THREAD

**Issue by geovanisouza92** [node-red/node-red-bluemix-nodes#27]
Hi, thank you or this library.

I'm trying to use the Speech to Text node to parse Telegram Bot API voice notes, but the node supports only WAV, while Telegram sends audio/ogg.

There is a way to put an option to select the file type, direct on node or through "msg"?

**Comment by knolleary** [comment]
The docs for the underlying Watson service do say ogg is supported - https://www.ibm.com/smarterplanet/us/en/ibmwatson/developercloud/doc/speech-to-text/using.shtml#formats - so we just need to find the right way to handle it.

Ideally it would just work, but I suspect trying to determine the right mime type would be hard to do.

Will have a look.
