### ISSUE TITLE
Change dynamically the source/destination languages for the Machine Translation

### ISSUE THREAD

**Issue by fchanson** [node-red/node-red-bluemix-nodes#31]
Hi,

the Machine Translation uses the node configuration for the source/destination languages.
It could be very interesting to override the node configuration using msg.srcLang and msg.destLang.

**Comment by jthomas** [comment]
Thanks for reporting this, I've implemented these changes in https://github.com/node-red/node-red-bluemix-nodes/commit/5a827a55dfd4dba9a2ea16cb3be23b72ffe29c8c.
