### ISSUE TITLE
Translation Service not working if target is different from English

### ISSUE THREAD

**Issue by zamrokk** [node-red/node-red-bluemix-nodes#34]
I got this error if I try to change the target to another language than English (on runtime / debug tab) : 

`    { "error_code": 404, "error_message": "cannot find service matching the request data" }
`
Could you please fix it  :)

PS: the bug was discovered during an IBM workshop session with students and potential customers.

**Comment by jthomas** [comment]
Thanks for reporting this issue. 
I've modified the nodes to restrict the drop-down options to ensure you don't select invalid source and destination languages.

**Comment by zamrokk** [comment]
How can i see the changes ? It seems I still have my node red with the buggy version

**Comment by knolleary** [comment]
They haven't been published to npm yet - will be shortly

**Comment by knolleary** [comment]
... and they have been now.

New instances of the boilerplate will get the fixed version. For an existing version, you'll need to restage your app after editing package.json to point at version 0.2.17 of node-red-bluemix-nodes.

**Comment by zamrokk** [comment]
Ok thank you

i see now that unavailable matches can not be selected    :)

just a question : Has Watson translation Service more combinations than the block available in NodeRed?

**Comment by jthomas** [comment]
Watson Translation came translate from English to a number of languages and back again. All the options in the service are available through Node-RED.
