### ISSUE TITLE
Add Weather company node to NODE RED

### ISSUE THREAD

**Issue by zamrokk** [node-red/node-red-bluemix-nodes#37]
Please can you add a new node "Weather" which is bound to the Weather Service in Bluemix ?

I have many requests for that : 
- in input, when a threshold of a value like temperature is over , then do something
- in input, when storms are expected in the next x hours, then do something

If I understand clearly, today if i want to do that i need to do a GET on the Weather API and use credentials. It could have been great to use the api directly in NodeRed without passing credentials if the service is already bound

Thanks

Ben

**Comment by jthomas** [comment]
Hey, I was actually just about to start working on this... 😀
Will have something ready later today hopefully!

**Comment by jthomas** [comment]
This has been done.
