### ISSUE TITLE
Documentation for adding a new node

### ISSUE THREAD

**Issue by kocolosk** [node-red/node-red-bluemix-nodes#41]
I imagine this is one of the most common types of Pull Requests you might get ... do you have the steps to add a node for a new service to node-red written down anywhere?

**Comment by hardillb** [comment]
http://nodered.org/docs/creating-nodes/

**Comment by knolleary** [comment]
@kocolosk hi - hopefully that link answers your question. If you have any further questions, please do follow up on the mailing list - https://groups.google.com/forum/#!forum/node-red
