### ISSUE TITLE
Move Watson nodes to their own repo

### ISSUE THREAD

**Issue by knolleary** [node-red/node-red-bluemix-nodes#44]
There's considerable interest in having the Watson nodes available to be installed outside of Bluemix. Whilst that is possible with the `node-red-bluemix-nodes` module, it does drag in the other Bluemix-specific nodes that aren't needed.

This issue is to track migrating the Watson nodes over to their own repo and ensure that everyone involves knows what's happening.

### Steps

1. Create new watson node module
 - [x] create `node-red-node-watson` repository - https://github.com/node-red/node-red-node-watson
 - [x] copy over the Watson nodes
 - [x] publish `node-red-node-watson` to npm

2. Update this repo
 - [x] remove watson nodes from this repo, including README etc
 - [x] publish new `1.0.0` version to npm - version bump important to preserve existing installs

3. Update Bluemix templates
 - Add `node-red-node-watson` to:
    - [x] [node-red-bluemix](https://github.com/node-red/node-red-bluemix/blob/master/public/app/package.json)
    - [x] [node-red-bluemix-starter](https://github.com/node-red/node-red-bluemix-starter/blob/master/package.json)
 - Update `node-red-bluemix-nodes` dependency to `1.x`
    - [x] [node-red-bluemix](https://github.com/node-red/node-red-bluemix/blob/master/public/app/package.json)
    - [x] [node-red-bluemix-starter](https://github.com/node-red/node-red-bluemix-starter/blob/master/package.json)
 - Publish updated `node-red-bluemix` to
    - [x] YS1 - us-south
    - [x] YS1 - eu-gb
    - [x] YP - us-south
    - [x] YP - eu-gb
 
### Outstanding items

@jthomas need your input on these...

 - [x] `tone_analyzer` nodes not in `package.json`
 - [x] `weather` nodes not in `package.json`
 - [x] should this include the `alchemy` nodes?

**Comment by jthomas** [comment]
Thanks for spotting my mistake, I'll update the package to include those two nodes.

Alchemy nodes should move across to the new Watson nodes package.

**Comment by knolleary** [comment]
All done
