### ISSUE TITLE
Weather Insights API is incorrect.

### ISSUE THREAD

**Issue by jaumemir** [node-red/node-red-bluemix-nodes#48]
It fails with a message: _Weather Insights service call failed with error HTTP response_.
Investigating, the code uses:
/api/weather/v2/forecast/daily/10day

when the API documentation (https://twcservice.mybluemix.net/rest-api/#) says:
/api/weather/v1/geocode/33.40/-83.42/forecast/daily/10day.json
being first number "latitude" and second one "longitude".

In general, seems that weatherinsights in bluemix uses V1 API while here seems it is using a V2 ¿?¿?

**Comment by patsmith-ibm** [comment]
Insights for Weather has been rebranded to Weather Company Data for IBM Bluemix and the APIs have been expanded. 

Unfortunately, the v2 APIs have been deprecated. There is a new set of v1 APIs available [here](https://twcservice.mybluemix.net/rest-api/).

**Comment by jthomas** [comment]
I have fixed the existing node to work with the new API paths.
In the future, we will hope to produce new nodes that encompass all the new API features as you suggest.
