### ISSUE TITLE
weather_insights result in "Weather Insights service call failed with error HTTP response"

### ISSUE THREAD

**Issue by Lokesh-K-Haralakatta** [node-red/node-red-bluemix-nodes#51]
Hi,
I'm trying to use weather_insgihts node in a Node-Red flow for very basic flow of getting current obervations for the lat,lon values of 45.42,75.69. I'm using the credentials from the bluemix service entered in to weather_insgihts node within Node-Red flow. When I deploy and request for weather data (I"m using trigger to request through Inject Node), the call fails and results with the error message - "Weather Insights service call failed with error HTTP response", even it does not say the HTTP Status Code.
I added node.log with in the weather_insights.js code to dump response.statusCode to find out that the returned HTTP Status Code is 401 which is UnAuthorized found from API page. I used the same credentials with the REST API to get current observations - https://username:password@twcservice.mybluemix.net:443/api/weather/v1/geocode/45.42/75.69/observations.json?units=m&language=en-US , I"m able to get the result with response code 200.

Am I missing anything to use weather_insights node?

**Comment by jthomas** [comment]
I've just tested my local install of the Weather Insights Node using [this flow](https://gist.githubusercontent.com/jthomas/c5033c59287dc5ee20054a58dda51541/raw/a9bdd1bdfbdde3cac396304eaaaaf0084cc144d4/flows.json) using my credentials and I can retrieve the results in Node-RED. 

Can you test this flow in your editor by importing the JSON (remembering to fill in your username and password in the edit dialog)?

**Comment by Lokesh-K-Haralakatta** [comment]
I imported the flow and filled in my credentials and selected the service as Observations, deployed the flow and triggered the flow, now I'm seeing 404 error.
Another difference I notice is the code difference between one available on github and the module installed from NPM. I have this version of module installed from NPM:

npm list node-red-bluemix-nodes
node-red@0.14.5 /Users/lharalak/github/node-red
└── node-red-bluemix-nodes@1.0.2 

Can you also please check the node available on NPM is with latest code as it's there on github?

**Comment by dceejay** [comment]
Hi - sorry - been on vacation... now published 1.0.4 to npm

**Comment by jthomas** [comment]
This should be resolved now, open the issue again if you have any further issues.

**Comment by Lokesh-K-Haralakatta** [comment]
Right, with 1.0.4 it's working fine. Thank you!
