### ISSUE TITLE
weather insights node  doesn't work in "United Kingdom" bluemix region.

### ISSUE THREAD

**Issue by janvda** [node-red/node-red-bluemix-nodes#52]
Hi,

My bluemix region = "United Kingdom" and not "US South".
FYI my bluemix URL = console.eu-gb.bluemix.net

Allthough I have bound the "Weather Company Data" service to my node-red application and restaged node-red, I still have to specify a user name and password when configuring a "weather insights" node in node-red.

As a test, I tried the same things in region "US South" and then I don't have this issue.

This is actually the same problem as reported in following link:
[http://stackoverflow.com/questions/36905385/bluemix-weather-node-of-nodered-is-always-throwing-call-failed-with-error-http]
The root cause of this problem is already identified by T. Smith in the first comment to this problem where he stated that
 "As you can see on [line 20](https://github.com/node-red/node-red-bluemix-nodes/blob/master/weather/weather_insights.js), the weather service host is hardcoded (twcservice.mybluemix.net) for the US-South region".

kr
Jan.

**Comment by jthomas** [comment]
If the service is bound to the instance, the node should pick up the host parameter from the service credentials.

https://github.com/node-red/node-red-bluemix-nodes/blob/master/weather/weather_insights.js#L31

This was added on April 19th. 

I've just tested deploying a new Node-RED instance in the UK region and binding a Weather Insights service to it. This has automatically picked up the service credentials and given me the API results. 

**Can you try following the same steps and seeing if you get the issue? Deploy a new Node-RED instance, provision a new Weather insights service, bind to Node-RED and restart the app.**

It might be the Node-RED instance, the version of the Weather Insights Node or the service credentials are outdated.

**Comment by jthomas** [comment]
I'm going to close this as now working, having tested myself. 
If you are still having issues, comment below and I'll re-open.
