### ISSUE TITLE
Weather Insights service call failed with error HTTP response.

### ISSUE THREAD

**Issue by smchamberlin** [node-red/node-red-bluemix-nodes#53]
Weather insights service was previously working for me a few days ago and now suddenly doesn't work anymore, and I don't believe I changed anything on my side.  I tried deleting the service and binding a brand new one, restaged my app and got the same result.

Msg doesn't flow through the node and here's what I'm seeing in the debug panel: "Weather Insights service call failed with error HTTP response."

I took a look at the code:
                if (!error && response.statusCode == 200) {
                    var results = JSON.parse(body);
                    msg.forecasts = results.forecasts;
                    msg.observation = results.observation;
                    msg.observations = results.observations;
                    node.send(msg);
                } else {
                    var message3 = 'Weather Insights service call failed with error HTTP response.';
                    node.error(message3, msg);
                }

so shouldn't the msg be shown in the debug panel, too?  Without knowing what we're getting back from the Weather Insights service itself, it's hard to know if this is a problem with the node, or the Weather Insights service is having problems or if they changed their API interface.  Please help!

**Comment by jthomas** [comment]
Thanks for reporting this. 
I *think* I've found the issue. 
There was an error with handling service credentials that could mean the HTTP response was returning a HTTP 401 Unauthorised response, which would lead to the error message you have seen. 

I've updated the error messages to be more specific about what HTTP response code is coming back and fixed the logic errors to prevent this issue happening. I was able to replicate the error message you saw locally and then resolve it with my changes. 

Once the new version is published on NPM, can you update the node and try again? 
I'm closing this ticket as fixed. If you are still having problems, update the ticket and I'll re-open and investigate further.

**Comment by smchamberlin** [comment]
Thanks James -- I restaged my application, and it works now!  I also noticed that the format of the msg object returned is totally different now ...  Guess the weather service must have changed things on their end; wonder if that could have affected things somehow, but anyway it's working. Thanks!

**Comment by jthomas** [comment]
That's correct, there was a recent API change. They have added lots more capabilities!
