### ISSUE TITLE
Add an option to allow language specification for Weather service

### ISSUE THREAD

**Issue by stevenatkin** [node-red/node-red-bluemix-nodes#54]
An option for specifying the language programmatically needs to be added to the weather service. Currently, this can only be set in the plugin panel. One possibility would be to add msg.language as one of the supported configurable variables.

**Comment by jthomas** [comment]
Thanks for the feedback. This is now supported using the standard "language" parameter on msg.

**Comment by stevenatkin** [comment]
Perfect. I just verified it works.
