### ISSUE TITLE
Trying to read a wav file for speech to text conversation node in node Red

### ISSUE THREAD

**Issue by george1784** [node-red/node-red-bluemix-nodes#55]
Hello 

I'm trying to read a blob file (wav audio file recorded in a web page) that i'm sending from a javascript, pass it to speech to text node and return the result. Problem is that i couldn't figure our which is the correct way to process data in node red. Here's how i'm sending info: 

 function createDownloadLink() {
    recorder && recorder.exportWAV(function(blob) {
      var url = URL.createObjectURL(blob);
      //TODO
      var fd = new FormData();
      //fd.append('fname', 'test.wav');
      fd.append('data', blob);

      $.ajax({
        type: 'POST',
        cache: false,
        url: '<nodered_url>/audioTest/',
        data: fd,
        processData: false,
        contentType: false,
        success: function(data) { 
          var r = JSON.stringify(data);
          console.log(r)//This is where Your users are
        }
      });
   });

Browser recognizes info as following (developer console): 

Request Headers
Accept:*/*
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,es;q=0.6
Connection:keep-alive
Content-Length:344285
Content-Type:multipart/form-data; boundary=----WebKitFormBoundaryIpSdL2SfBA5pIOWx
Host:testjj.mybluemix.net
Origin:null
User-Agent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.116 Safari/537.36

Request Payload
------WebKitFormBoundaryIpSdL2SfBA5pIOWx
Content-Disposition: form-data; name="data"; filename="blob"
Content-Type: audio/wav

In node red after the http node i have a function node with following code:

const buf = new Buffer( msg.payload, 'hex');
msg.payload = buf;
return msg;

But as soon as info pass to speech to text node following error appears

TypeError: Cannot read property 'ext' of null

Appreciate your comments on this issue

Best Regards

**Comment by jthomas** [comment]
Hello. 

The IBM Watson nodes for Node-RED are now being managed in a separate repository (https://github.com/watson-developer-cloud/node-red-node-watson). Could you re-open this ticket in that repo and the team will investigate for you?
